version: 2

jobs:
  lint:
    docker:
      - image: web3f/ci-commons:v2.3.1
    steps:
      - checkout
      - run:
          command: |
            echo lint

  buildImage:
    docker:
      - image: web3f/ci-commons:v2.3.1
    steps:
      - checkout
      - run:
          command: |
            echo build

  integrationTests:
    docker:
      - image: web3f/ci-commons:v2.3.1
    steps:
      - checkout
      - run:
          description: run integration tests
          command: |
            echo integration test

  publishImage:
    docker:
      - image: web3f/ci-commons:v2.3.1
    steps:
      - checkout
      - run:
          command: |
            publish image

  publishChart:
    docker:
      - image: web3f/ci-commons:v2.3.1
    steps:
      - checkout
      - run:
          command: |
            publish chart

  deployProduction:
      docker:
        - image: web3f/ci-commons:v2.3.1
      steps:
        - checkout
        - run:
            command: |
              echo "deploy production"

  deployStaging:
      docker:
        - image: web3f/ci-commons:v2.3.1
      steps:
        - checkout
        - run:
            command: |
              echo deploy staging


workflows:
  version: 2
  test_and_deploy:
    jobs:
      - lint:
          filters:
            tags:
              only: /.*/
      - buildImage:
          filters:
            tags:
              only: /.*/
      - integrationTests:
          filters:
            tags:
              only: /.*/
          requires:
            - lint
            - buildImage
      - publishImage:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*$/
          requires:
            - integrationTests
      - publishChart:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*$/
          requires:
            - integrationTests
      - deployStaging:
          filters:
            branches:
              only: /staging/
          requires:
            - integrationTests
      - deployProduction:
          filters:
            branches:
              only: /production/
            tags:
              only: /v[0-9]+(\.[0-9]+)*$/
          requires:
            - publishImage
            - publishChart
